variable "cluster_name" {}
variable "stage" {}
variable "cluster_id" {}
variable "cluster_endpoint" {}
variable "vpc_name" {}
variable "vpc_cidr" {}
variable "vpc_id" {}
variable "waf_arn" {}
variable "region" {}
variable "master_auth" {}
variable "token" {}
variable "docker_repository" {}
variable "deploy_to_where" {}
variable "firewall_default" {}
variable "whitelisted_ips" {}

variable "guardian_access_token_secret" {}
variable "guardian_topic_id" {}
variable "guardian_operator_id" {}
variable "guardian_operator_key" {}
variable "guardian_ipfs_key" {}
variable "guardian_version" {}
variable "guardian_max_transaction_fee" {}
variable "guardian_initial_balance" {}