apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
#allowedTopologies:
#- matchLabelExpressions:
#  - key: failure-domain.beta.kubernetes.io/zone
#    values:
#    - ap-southeast-2a
#  - key: topology.kubernetes.io/zone
#    values:
#    - ap-southeast-2a