apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: mongo-snapshot-class
driver: pd.csi.storage.gke.io
deletionPolicy: Delete

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-existing-disk
# spec:
#   storageClassName: ""
#   capacity:
#     storage: 150Gi
#   accessModes:
#     - ReadWriteOnce
#   gcePersistentDisk:
#     pdName: mongo-db-pvc
#     fsType: ext4
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-existiting-disk
# spec:
#   storageClassName: ""
#   volumeName: pv-existing-disk
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 150Gi
