apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: pd.csi.storage.gke.io
  creationTimestamp: "2022-09-26T23:41:40Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/pd-csi-storage-gke-io
  name: mongo-db-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: datadir-mongodb-0
    namespace: default
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1664234660877-8081-pd.csi.storage.gke.io
    volumeHandle: projects/tymlez-dev-240712/zones/australia-southeast1-b/disks/mongodb
  storageClassName: standard-rwo
  volumeMode: Filesystem

# https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/preexisting-pd