apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-logger-service.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: message-broker
  DB_HOST: mongodb
  DB_DATABASE: logger_db
  SERVICE_CHANNEL: "logger-service"
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  NEW_RELIC_APP_NAME: "{{ include "guardian-logger-service.fullname" . }}"
  MQ_MESSAGE_CHUNK: "{{ .Values.global.guardian.mq_message_chunk}}"
