# Default values for guardian-logger-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: p3001
      protocol: TCP
      name: p3001

replicaCount: 1

image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: 
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  initialDelaySeconds: 30
  failureThreshold: 10
  timeoutSeconds: 5
  exec:
    command: 
      - /bin/bash
      - -c
      - ps aux | grep index.js
readinessProbe:
  initialDelaySeconds: 30
  failureThreshold: 10
  timeoutSeconds: 5
  exec:
    command: 
      -  node 
      -  guardian-healthcheck.js