apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-application-events.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: message-broker
  DB_HOST: mongodb
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  NEW_RELIC_APP_NAME: "{{ include "guardian-application-events.fullname" . }}"
  MONGODB_SERVER_URL: mongodb://mongodb:27017