apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-extensions.name" . }}-newrelic
data:
  NEW_RELIC_ENABLED: "{{ .Values.global.enable_newrelic}}"
  NEW_RELIC_LOG_ENABLED: "true"
  NEW_RELIC_TRACER_ENABLED: "true"
  NEW_RELIC_LICENSE_KEY: "{{ .Values.global.newrelic_license_key}}"
  NEW_RELIC_NO_CONFIG_FILE: "true"
  NEW_RELIC_LABELS: "{{ .Values.global.apm_labels}}"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-extensions.name" . }}-shared
data:
  MQ_MAX_PAYLOAD: "10485760"
  MQ_MESSAGE_CHUNK: "{{ .Values.global.guardian.mq_message_chunk}}"
  MESSAGE_LANG: "en-US"
  PREUSED_HEDERA_NET: "{{ .Values.global.guardian.network}}"
  GUARDIAN_ENV: ""
  HEDERA_NET: "{{ .Values.global.guardian.network}}"
  ENV: ""