apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tymlez-extensions.fullname" . }}-newrelic
data:
  NEW_RELIC_ENABLED: "true"
  NEW_RELIC_LOG_ENABLED: "true"
  NEW_RELIC_TRACER_ENABLED: "true"
  NEW_RELIC_LICENSE_KEY: "{{ .Values.global.nrLicenseKey}}"
  NEW_RELIC_NO_CONFIG_FILE: "true"
  NEW_RELIC_LABELS: "env:{{ .Values.global.env}};client:{{ .Values.global.clientName }}"
  NEW_RELIC_APPLICATION_LOGGING_FORWARDING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED: "true"
  NEW_RELIC_APPLICATION_LOGGING_METRICS_ENABLED: "true"
