apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-ipfs-client.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: message-broker
  DB_HOST: mongodb
  DB_DATABASE: ipfs_client_db
  SERVICE_CHANNEL: "ipfs-client"
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  NEW_RELIC_APP_NAME: "{{ include "guardian-ipfs-client.fullname" . }}"
  MQ_MESSAGE_CHUNK: "{{ .Values.global.guardian.mq_message_chunk}}"