apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardian-ipfs-client.fullname" . }}-{{ .Release.Revision }}
type: Opaque
data:
  IPFS_STORAGE_API_KEY: {{ .Values.global.guardian.ipfsKey | b64enc | quote }}