apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardian-ipfs-client.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "guardian-ipfs-client.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "guardian-ipfs-client.selectorLabels" . | nindent 4 }}