apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-frontend.fullname" . }}-{{ .Release.Revision }}
data:  
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location /ws/ {
            proxy_pass http://guardian-api-gateway:3002;
            proxy_set_header Host $host;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 120s;
        }

        location /api/v1/ {
            proxy_pass http://guardian-api-gateway:3002/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Surrogate-Control no-store;
            proxy_set_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";
            proxy_set_header Pragma no-cache;
            proxy_set_header Expires 0;
            proxy_redirect off;
        }

        location / {
            root   /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/local/share/nginx/html;
        }
    }