version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - 27017

  api-docs:
      image: ${DOCKER_REPOSITORY}/api-docs:latest
    expose:
      - 3001

  message-broker:
    image: nats
    expose:
      - 4222
    ports:
      - '8222:8222'
    command: '--http_port 8222'

  logger-service:
    image: ${DOCKER_REPOSITORY}/logger-service:latest
    depends_on:
      - message-broker

  auth-service:
    image: ${DOCKER_REPOSITORY}/auth-service:latest
    depends_on:
      - mongo
      - message-broker
      - logger-service

  api-gateway:
    image: ${DOCKER_REPOSITORY}/api-gateway:latest
    expose:
      - 3002
    depends_on:
      - mongo
      - message-broker
      - guardian-service
      - auth-service
      - logger-service

  guardian-service:
    image: ${DOCKER_REPOSITORY}/guardian-service:latest
    depends_on:
      - mongo
      - message-broker
      - auth-service
      - logger-service

  ipfs-client:
    image: ${DOCKER_REPOSITORY}/ipfs-client:latest
    ports:
      - "5001:5001"
      - "5002:5002"
      - "4001:4001"
      - "4002:4002"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - message-broker
      - logger-service

#  mrv-sender:
#    image: ${DOCKER_REPOSITORY}/mrv-sender:latest
#    expose:
#      - 3005

  topic-viewer:
    image: ${DOCKER_REPOSITORY}/topic-viewer:latest
    expose:
      - 3006

  web-proxy:
    image: ${DOCKER_REPOSITORY}/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - guardian-service
      - auth-service
      - api-gateway
      - api-docs
#      - mrv-sender
volumes:
  mongo:
  # volume-guardian-service:
  # volume-message-broker:
