apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardian-web-proxy.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "guardian-web-proxy.labels" . | nindent 4 }}
  annotations:
    {{- include "guardian-web-proxy.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "guardian-web-proxy.selectorLabels" . | nindent 4 }}
{{/*  loadBalancerIP: {{ .Values.global.guardian.staticIp }}*/}}
