apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-api-gateway.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: message-broker
  SERVICE_CHANNEL: api-gateway
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  NEW_RELIC_APP_NAME: "{{ include "guardian-api-gateway.fullname" . }}"
  HEALCHECK_CHANNEL_NAME: guardians