apiVersion: v1
kind: Service
metadata:
  name: {{ include "guardian-worker-service.fullname" . }}-{{ .Release.Revision }}
  labels:
    {{- include "guardian-worker-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "guardian-worker-service.selectorLabels" . | nindent 4 }}