apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-guardian-service.fullname" . }}-{{ .Release.Revision }}
data:
  MQ_ADDRESS: message-broker
  DB_HOST: mongodb
  DB_DATABASE: guardian_db
  SERVICE_CHANNEL: "guardians"
  MAX_TRANSACTION_FEE: {{ .Values.global.guardian.maxTransactionFee | quote }}
  INITIAL_BALANCE: {{ .Values.global.guardian.initialBalance | quote }}
  INITIAL_STANDARD_REGISTRY_BALANCE: "{{ .Values.global.guardian.initialStandardRegistryBalance}}"
  INITIALIZATION_TOPIC_ID: "{{ .Values.global.guardian.initializationTopicId}}"
  HEDERA_NET: "{{ .Values.global.guardian.network}}"
  MESSAGE_LANG: "en-US"
  LOG_LEVEL: "{{ .Values.global.guardian.logLevel}}"
  ENABLE_APM_NAME: "{{ .Values.global.guardian.enable_apm_name }}"
  NEW_RELIC_APP_NAME: "{{ include "guardian-guardian-service.fullname" . }}"
  NODE_OPTIONS: "--max-old-space-size=8192"
  MULTI_POLICY_SCHEDULER: "0 0 * * *"
  SEND_KEYS_TO_VAULT: "TRUE"
  CONTRACT_FILE_ID: "0.0.6276"
  BBS_SIGNATURES_MODE: "WASM"
  MQ_MESSAGE_CHUNK: "{{ .Values.global.guardian.mq_message_chunk}}"
