apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-guardian-service.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: guardian-message-broker-{{ .Release.Revision }}
  DB_HOST: mongodb
  DB_DATABASE: guardian_db
  SERVICE_CHANNEL: "guardian.1"
  OPERATOR_ID: {{ .Values.global.guardian.operatorId }}
  OPERATOR_KEY: {{ .Values.global.guardian.operatorKey }}
  SCHEMA_TOPIC_ID: {{ .Values.global.guardian.topicId }}
 