apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardian-guardian-service.fullname" . }}-{{ .Release.Revision }}
type: Opaque
data:
  OPERATOR_ID: {{ .Values.global.guardian.operatorId | b64enc | quote }}
  OPERATOR_KEY: {{ .Values.global.guardian.operatorKey | b64enc | quote}}