apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "guardian-auth-service.fullname" . }}-{{ .Release.Revision }}
data:  
  MQ_ADDRESS: message-broker
  DB_HOST: mongodb
  DB_DATABASE: auth_db
  SERVICE_CHANNEL: auth-service
  ACCESS_TOKEN_SECRET: {{ .Values.global.guardian.accessTokenSecret }}
 