apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guardian-auth-service.fullname" . }}-{{ .Release.Revision }}
type: Opaque
data:
  ACCESS_TOKEN_SECRET: {{ .Values.global.guardian.accessTokenSecret | b64enc | quote}}